linters:
  enable-all: true
  disable:
    # Should eventually address, aiming for basic MVP ATM :)
    - varnamelen
    - wrapcheck
    - forbidigo
    - dupl
    - lll
    - cyclop
    - funlen
    - mnd
    - gosec
    - depguard
    - err113
    - exhaustruct
